In [13]:
import numpy as np
np.random.seed(42)

np.random.default_rng(234)

Generator(PCG64) at 0x27E35865A80

# Tasks

# Practice

In [6]:
vector_1D = np.array([10, 20, 30])
print(f"Row vector \n{vector_1D}")

vector_2D = np.array([[10], [20], [30]])
print(f"Column vector: \n{vector_2D}")

Row vector 
[10 20 30]
Column vector: 
[[10]
 [20]
 [30]]


In [ ]:
# Vector Addition
a = np.array([2, 3])
b = np.array([1, 5])
print(f"a + b = {a+b}")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


a + b = [3 8]


In [8]:
# Scalar Multiplication 
prices = np.array([100, 200])
double = 2
print(f"Double price: {double * prices}")

Double price: [200 400]


## Practice Questions
Create a 3x3 matrix of random integers and:

   - Multiply it by 2

   - Transpose it

   - Find the determinant

   - Check if it’s invertible

   - If yes, find the inverse


In [27]:
ran = np.random.randint(1,10, size=(3,3))
print(ran)
ran.T
print(f"\nTranspose \n{ran.T}")

print(f"\nDeterminant: \n{np.linalg.det(ran)}")
print(f"\nNon invertible: {(np.linalg.det(ran))!=0}")
print(f"\nInverse: \n{np.linalg.inv(ran)}")

[[9 5 6]
 [4 7 9]
 [7 1 1]]

Transpose 
[[9 4 7]
 [5 7 1]
 [6 9 1]]

Determinant: 
7.000000000000034

Non invertible: True

Inverse: 
[[-0.28571429  0.14285714  0.42857143]
 [ 8.42857143 -4.71428571 -8.14285714]
 [-6.42857143  3.71428571  6.14285714]]
